### ISSUE TITLE
wiki 상단 이미지 글자 색

### ISSUE THREAD

**Issue by ujiyun** [OSS2023UY/2023osstest#7]
wiki에서 상단 이미지에 UYteam이라고 써진 글자의 색을 흰색으로 바꾸고 싶은데 저는 아무리 해도 잘 되지 않아서 혹시 시간 괜찮으실 때 도와주시면 감사하겠습니다:)

**Comment by HSKYOO** [comment]
아래 OSS Mini Project는 하얀색으로 만들었는데 UY Team 글자가 사라져서 보이네요 혹시 확인해주실 수 있나요?

**Comment by HSKYOO** [comment]
바꿔습니다!

**Comment by ujiyun** [comment]
우와 감사합니다!!!!
